# Generated by Django 5.2.13 on 2026-05-17 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='scope',
            field=models.CharField(choices=[('private', 'Private'), ('global', 'Global')], db_index=True, default='private', max_length=16),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('leave_approved', 'Leave Approved'), ('leave_rejected', 'Leave Rejected'), ('shift_cancelled', 'Shift Cancelled'), ('assignment_created', 'Assigned to Shift'), ('payroll_approved', 'Payroll Approved'), ('payroll_paid', 'Payroll Paid'), ('announcement', 'Announcement')], db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='NotificationRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='notifications.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Read',
                'unique_together': {('notification', 'user')},
            },
        ),
    ]
