# Generated by Django 5.2.13 on 2026-05-17 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftassignment',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
