# Generated by Django 5.2.13 on 2026-05-14 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('branch_created', 'Branch Created'), ('branch_updated', 'Branch Updated'), ('branch_deleted', 'Branch Deleted'), ('employment_created', 'Employment Created'), ('employment_updated', 'Employment Updated'), ('employment_deleted', 'Employment Deleted'), ('shift_created', 'Shift Created'), ('shift_updated', 'Shift Updated'), ('shift_cancelled', 'Shift Cancelled'), ('assignment_created', 'Assignment Created'), ('assignment_removed', 'Assignment Removed'), ('assignment_checked_in', 'Assignment Checked In'), ('assignment_checked_out', 'Assignment Checked Out'), ('leave_created', 'Leave Created'), ('leave_approved', 'Leave Approved'), ('leave_rejected', 'Leave Rejected'), ('leave_cancelled', 'Leave Cancelled')], db_index=True, max_length=64)),
                ('resource_type', models.CharField(db_index=True, max_length=64)),
                ('resource_id', models.CharField(blank=True, max_length=64)),
                ('resource_name', models.CharField(blank=True, max_length=256)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
