# Generated by Django 5.2.13 on 2026-04-18 21:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('supervisor', 'Supervisor'), ('staff', 'Staff')], max_length=30)),
                ('hire_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('terminated', 'Terminated'), ('suspended', 'Suspended')], default='active', max_length=30)),
                ('termination_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employments', to='branches.branch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Compensation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('hourly', 'Hourly'), ('monthly', 'Monthly'), ('shift_based', 'Shift based')], max_length=30)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('base_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bonus_type', models.CharField(choices=[('none', 'None'), ('fixed', 'Fixed'), ('percent', 'Percent')], default='none', max_length=20)),
                ('bonus_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensations', to='employment.employment')),
            ],
            options={
                'db_table': 'compensation',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.AddConstraint(
            model_name='employment',
            constraint=models.UniqueConstraint(fields=('user', 'branch', 'hire_date'), name='unique_employment_per_user_branch_hire_date'),
        ),
    ]
